table 'Customer Lookup'
	excludeFromModelRefresh
	lineageTag: b6f57b73-23fc-4649-8f5c-e1a67f2faf74

	column CustomerKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: a97d1e8d-5306-401c-a0fb-d1502f158006
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column Prefix
		dataType: string
		lineageTag: 33649c16-97cd-481b-bab7-3e898363071d
		summarizeBy: none
		sourceColumn: Prefix

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 928fbd73-7a49-4bd7-8622-24c6cf350aa5
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 7fcc9ffe-e17a-4765-a54b-4eb823241171
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 54ff7b7c-3fba-44b0-910c-fbcf75987c01
		summarizeBy: none
		sourceColumn: BirthDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MaritalStatus
		dataType: string
		lineageTag: bd994389-7ddb-488b-a827-347fa233e892
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 2061977a-b3b5-4009-a1b2-3dac8e29c12f
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: 8a055752-b4ec-406c-b15d-0e7a3d5cfb46
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column AnnualIncome
		dataType: int64
		formatString: 0
		lineageTag: 4007688f-9afe-4a9e-a628-f57860ab472b
		summarizeBy: none
		sourceColumn: AnnualIncome

		annotation SummarizationSetBy = Automatic

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: 58d04491-44a8-41db-b0dc-001ab66113fc
		summarizeBy: none
		sourceColumn: TotalChildren

		annotation SummarizationSetBy = Automatic

	column EducationLevel
		dataType: string
		lineageTag: 22815412-beaf-4af1-81d9-b575cf3bc87e
		summarizeBy: none
		sourceColumn: EducationLevel

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: 522fc35e-094e-48ac-8c3d-1b30644049d3
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column HomeOwner
		dataType: string
		lineageTag: b83223bf-15f9-4143-a466-41a2df9dee0b
		summarizeBy: none
		sourceColumn: HomeOwner

		annotation SummarizationSetBy = Automatic

	column 'Full Name'
		dataType: string
		lineageTag: 29586ac8-119a-4072-a82a-48a4636683df
		summarizeBy: none
		sourceColumn: Full Name

		annotation SummarizationSetBy = Automatic

	column 'Domain Name'
		dataType: string
		lineageTag: e5fe8c52-436a-4337-b4d3-82e10da654f3
		summarizeBy: none
		sourceColumn: Domain Name

		annotation SummarizationSetBy = Automatic

	column 'Is Parent?' = ```
			
			IF(
			    'Customer Lookup'[TotalChildren] > 0, 
			    "Yes",
			    "No"
			)
			```
		lineageTag: dc72b724-4b0c-45af-bdf3-adeb9700d381
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer Full Name (CC)' =
			
			'Customer Lookup'[Prefix] & " " & 'Customer Lookup'[FirstName] & " " & 'Customer Lookup'[LastName]
		lineageTag: 3257c4a3-a83f-4969-89de-c1eb9d67f9cf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer Priority' =
			
			IF(
			    'Customer Lookup'[AnnualIncome] > 100000 &&
			    'Customer Lookup'[Is Parent?] = "Yes",
			    "Priority",
			    "Standard"
			)
		lineageTag: dbe0824e-1b5f-4faf-9c24-dcc07c48bcf0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Birth Year' =
			
			YEAR(
			    'Customer Lookup'[BirthDate]
			)
		formatString: 0
		lineageTag: ae7afcf7-e719-4986-b140-01edeeba5777
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Income Level' =
			
			IF('Customer Lookup'[AnnualIncome] >= 150000, "Very High",
			IF('Customer Lookup'[AnnualIncome] >= 100000, "High",
			IF('Customer Lookup'[AnnualIncome] >= 50000, "Average",
			"Low")))
		lineageTag: af320bb5-cc74-49fd-94aa-d28faa981c38
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Education Category' =
			
			SWITCH(
			    'Customer Lookup'[EducationLevel],
			    "High School", "High School",
			    "Partial High School", "High School",
			    "Bachelors", "Undergrad",
			    "Partial College", "Undergrad",
			    "Graduate Degree", "Graduate"
			)
		lineageTag: 09f9e9dd-b545-4c81-94dc-fb306a1e1b38
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Customer Lookup-4ef9da10-e6c4-427d-81b9-371361091174' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ampar\OneDrive\Desktop\Adventure Works Raw Data\AdventureWorks Customer Lookup.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerKey", Int64.Type}, {"Prefix", type text}, {"FirstName", type text}, {"LastName", type text}, {"BirthDate", type date}, {"MaritalStatus", type text}, {"Gender", type text}, {"EmailAddress", type text}, {"AnnualIncome", Int64.Type}, {"TotalChildren", Int64.Type}, {"EducationLevel", type text}, {"Occupation", type text}, {"HomeOwner", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"CustomerKey"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Errors", each [CustomerKey] <> null and [CustomerKey] <> ""),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Filtered Rows",{{"Prefix", Text.Proper, type text}, {"FirstName", Text.Proper, type text}, {"LastName", Text.Proper, type text}}),
				    #"Inserted Full Name Column" = Table.AddColumn(#"Capitalized Each Word", "Full Name", each Text.Combine({[Prefix], [FirstName], [LastName]}, " "), type text),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Inserted Full Name Column", "EmailAddress", "EmailAddress - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"EmailAddress - Copy", "Domain Name"}}),
				    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Renamed Columns", {{"Domain Name", each Text.AfterDelimiter(_, "@"), type text}}),
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Extracted Text After Delimiter", {{"Domain Name", each Text.BeforeDelimiter(_, "."), type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Extracted Text Before Delimiter","-"," ",Replacer.ReplaceText,{"Domain Name"}),
				    #"Capitalized Each Word1" = Table.TransformColumns(#"Replaced Value",{{"Domain Name", Text.Proper, type text}})
				in
				    #"Capitalized Each Word1"

	annotation PBI_ResultType = Table

