table 'Product Lookup'
	excludeFromModelRefresh
	lineageTag: 86067e73-c82c-47c5-9fb8-0d0d533d22a9

	column ProductKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: eac77070-10d2-4940-b280-6daf314edb7a
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4c4ece70-1f38-44f9-bc94-a5d6031b6db4
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductSKU
		dataType: string
		lineageTag: 6dbd90e3-9ffe-4878-9f03-9fcfd094316d
		summarizeBy: none
		sourceColumn: ProductSKU

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: fbfa4178-6f74-4100-8498-72a3e12f3c56
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column ModelName
		dataType: string
		lineageTag: ba127af3-9268-4166-8571-9650ab9f7c48
		summarizeBy: none
		sourceColumn: ModelName

		annotation SummarizationSetBy = Automatic

	column ProductDescription
		dataType: string
		lineageTag: c98c9fee-2ee2-4491-9382-cad22340ce71
		summarizeBy: none
		sourceColumn: ProductDescription

		annotation SummarizationSetBy = Automatic

	column ProductColor
		dataType: string
		lineageTag: 6baeeeb9-51fe-4c9b-a385-0f861125881f
		summarizeBy: none
		sourceColumn: ProductColor

		annotation SummarizationSetBy = Automatic

	column ProductStyle
		dataType: string
		lineageTag: 8fa2cd78-5e88-4c0c-8dac-ecacde3adaed
		summarizeBy: none
		sourceColumn: ProductStyle

		annotation SummarizationSetBy = Automatic

	column ProductCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 947f5588-1e8f-47e6-ae48-c43d3e61392c
		summarizeBy: sum
		sourceColumn: ProductCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ProductPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 26d29de6-4c0f-4715-a373-2faa721d5313
		summarizeBy: sum
		sourceColumn: ProductPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'SKU Type'
		dataType: string
		lineageTag: 9a88122a-e721-4b76-881e-3d8bb4ba499c
		summarizeBy: none
		sourceColumn: SKU Type

		annotation SummarizationSetBy = Automatic

	column 'Discount Price'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: dff279ff-4b93-4128-b815-6722fbf17d81
		summarizeBy: sum
		sourceColumn: Discount Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Price Point' =
			
			SWITCH(
			    TRUE(),
			    'Product Lookup'[ProductPrice] > 500, "High",
			    'Product Lookup'[ProductPrice] > 100, "Mid-Range",
			    "Low"
			)
		lineageTag: 3ed5a513-dbdb-4b9d-95a4-bd78e3fc97b8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'SKU Category' =
			
			LEFT(
			    'Product Lookup'[ProductSKU],
			    SEARCH(
			        "-",
			        'Product Lookup'[ProductSKU]
			    )
			    -1
			)
		lineageTag: e94513fa-4841-4648-89ef-9f779b2da10a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Product Lookup-e955de83-5d7a-47cb-aa05-c4d09bf9ba33' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ampar\OneDrive\Desktop\Adventure Works Raw Data\AdventureWorks Product Lookup.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", Int64.Type}, {"ProductSubcategoryKey", Int64.Type}, {"ProductSKU", type text}, {"ProductName", type text}, {"ModelName", type text}, {"ProductDescription", type text}, {"ProductColor", type text}, {"ProductSize", type text}, {"ProductStyle", type text}, {"ProductCost", type number}, {"ProductPrice", type number}}),
				    #"Changed to Currency" = Table.TransformColumnTypes(#"Changed Type",{{"ProductCost", Currency.Type}, {"ProductPrice", Currency.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed to Currency",{"ProductSize"}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Removed Columns", "Text Before Delimiter", each Text.BeforeDelimiter([ProductSKU], "-", 1), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", "SKU Type"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","0","NA",Replacer.ReplaceText,{"ProductStyle"}),
				    #"Inserted Multiplication" = Table.AddColumn(#"Replaced Value", "Multiplication", each [ProductPrice] * 0.9, Currency.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Multiplication",{{"Multiplication", "Discount Price"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

