table 'Product Subcategories Lookup'
	excludeFromModelRefresh
	lineageTag: 9477f77d-bf9a-4b33-876a-8cc6fab5a2e3

	column ProductSubcategoryKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 9867245c-a9f0-401d-b971-cb6376547c84
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column SubcategoryName
		dataType: string
		lineageTag: ce5e6b13-e6d0-4f3d-8b8b-27d4b4e9ebcd
		summarizeBy: none
		sourceColumn: SubcategoryName

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 14f1a47a-2719-48a7-86c7-895581ec1deb
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Product Subcategories Lookup-a4486965-3d1e-4885-8330-4c601a97414c' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ampar\OneDrive\Desktop\Adventure Works Raw Data\AdventureWorks Product Subcategories Lookup.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductSubcategoryKey", Int64.Type}, {"SubcategoryName", type text}, {"ProductCategoryKey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

