table 'Product Categories Lookup'
	excludeFromModelRefresh
	lineageTag: 3560f8c6-f00d-4219-81fd-61ca5f8dbd11

	column ProductCategoryKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 102d0295-832c-4ba7-bb2b-ad9719adb787
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: 766456d6-f2c4-4d99-84f7-65033c26b4f0
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	partition 'Product Categories Lookup-46e150a7-7b7d-49a8-827f-79ec8ba05b10' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ampar\OneDrive\Desktop\Adventure Works Raw Data\AdventureWorks Product Categories Lookup.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductCategoryKey", Int64.Type}, {"CategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

