table 'Returns Data'
	lineageTag: 6ec0d48c-2d8b-4d22-8b17-2459a2eb70e8

	column ReturnDate
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 34de9767-48c5-401c-9ab4-00420d7ea382
		summarizeBy: none
		sourceColumn: ReturnDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7af43c6c-7a36-4983-bdb7-d681b55ff4ac
		summarizeBy: none
		sourceColumn: TerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: aeb27194-8c6a-4be1-bae7-828e49d0dd69
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ReturnQuantity
		dataType: int64
		formatString: 0
		lineageTag: d267704f-57ae-419c-811e-09423885e916
		summarizeBy: sum
		sourceColumn: ReturnQuantity

		annotation SummarizationSetBy = Automatic

	partition 'Returns Data-61fde16b-e427-4246-88cc-b79819177f01' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ampar\OneDrive\Desktop\Adventure Works Raw Data\AdventureWorks Returns Data.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ReturnDate", type date}, {"TerritoryKey", Int64.Type}, {"ProductKey", Int64.Type}, {"ReturnQuantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

