table 'Sales Data'
	lineageTag: a175a6e1-b904-49df-8c98-e9cafd97874a

	column OrderDate
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 067564fd-2a5a-4acb-a0f3-f1924fe762d2
		summarizeBy: none
		sourceColumn: OrderDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StockDate
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 08645b6f-6c05-4305-90aa-f397bf3cdadd
		summarizeBy: none
		sourceColumn: StockDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderNumber
		dataType: string
		lineageTag: 27f9a1f4-80af-4b3a-bfe8-923e759fc86c
		summarizeBy: none
		sourceColumn: OrderNumber

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 95be199f-67d1-4802-b88d-125c1e9abf97
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: faf77e53-12d6-4c6a-bdf8-f775572a777d
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 21d20fbf-ce6a-441b-8491-934899161ba2
		summarizeBy: none
		sourceColumn: TerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderLineItem
		dataType: int64
		formatString: 0
		lineageTag: f31adfa0-923a-433e-98d8-1bf3aeb71517
		summarizeBy: sum
		sourceColumn: OrderLineItem

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: aed61bc3-63ff-4f57-b134-8fb06e2b1843
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column 'Quantity Type' = ```
			
			IF(
			    'Sales Data'[OrderQuantity] > 1, 
			    "Multiple Items", 
			    "Single Item"
			)
			```
		lineageTag: 01beb9a2-1211-4867-aceb-7f4436990566
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Retail Price' =
			
			RELATED(
			    'Product Lookup'[ProductPrice]
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cdebfcb2-e55e-4992-bbec-23a39b6561b5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Revenue =
			
			'Sales Data'[Retail Price] * 'Sales Data'[OrderQuantity]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: af2003c9-a70f-4fc6-bbe0-dc3f1b34573a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition 'Sales Data-51f84d21-8b73-4775-bea3-3170b5be73db' = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\ampar\OneDrive\Desktop\Adventure Works Raw Data\Sales Data"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"OrderDate", type date}, {"StockDate", type date}, {"OrderNumber", type text}, {"ProductKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"TerritoryKey", Int64.Type}, {"OrderLineItem", Int64.Type}, {"OrderQuantity", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

