table 'Static-Candidate RFPs'
	isHidden
	lineageTag: 16d8139b-005f-4398-b971-109c5d3de8ac

	column 'CRM Opportunity ID'
		dataType: string
		isHidden
		lineageTag: 086560d9-f262-4303-93fa-d65f71e86cdc
		summarizeBy: none
		sourceColumn: CRM Opportunity ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Timezone
		dataType: string
		lineageTag: 6d8f0e82-e2f3-4b01-aec1-3f1b7154c23d
		summarizeBy: none
		sourceColumn: Timezone

		annotation SummarizationSetBy = Automatic

	partition 'Static-Candidate RFPs-7f8a4bc6-b07f-43e1-89d0-59b903fa2740' = m
		mode: import
		queryGroup: 'Excel Org Alignment Tables'
		source =
				let
				    Source = SharePoint.Files("https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "Static Mappings - DO NOT MOVE OR DELETE THIS FILE.xlsx")),
				    #"Static Mappings- DO NOT MOVE OR DELETE THIS FILE.xlsx_https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/Shared Documents/General/Pursuit Management Insights/Static Files/" = #"Filtered Rows"{[Name="Static Mappings - DO NOT MOVE OR DELETE THIS FILE.xlsx",#"Folder Path"="https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/Shared Documents/General/Pursuit Management Insights/Static Files/"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"Static Mappings- DO NOT MOVE OR DELETE THIS FILE.xlsx_https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/Shared Documents/General/Pursuit Management Insights/Static Files/"),
				    #"Candidate RFPs_Sheet" = #"Imported Excel Workbook"{[Item="Candidate RFPs",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Candidate RFPs_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CRM Opportunity ID", type text}, {"Timezone", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

