table 'Static-Country Flags'
	isHidden
	lineageTag: 7984a589-75b4-4456-a01a-aac255bfc0f3

	column Subsidiary
		dataType: string
		isHidden
		lineageTag: 1fc06b9a-58c0-4c41-9cd8-f120d8a02520
		summarizeBy: none
		sourceColumn: Subsidiary

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Image
		dataType: string
		isHidden
		lineageTag: 1d459188-12f6-46cc-9703-4cc1748906c8
		summarizeBy: none
		sourceColumn: Image

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Timezone
		dataType: string
		lineageTag: 8382649d-14cf-4529-a432-acefba689d0e
		summarizeBy: none
		sourceColumn: Timezone

		annotation SummarizationSetBy = Automatic

	partition 'Static-Country Flags-42318916-132d-4a12-9b84-a866aa63b37c' = m
		mode: import
		queryGroup: 'Excel Org Alignment Tables'
		source =
				let
				    Source = SharePoint.Files("https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "Static Mappings - DO NOT MOVE OR DELETE THIS FILE.xlsx")),
				    #"Static Mappings-DO NOT MOVE OR DELETE THIS FILE.xlsx_https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/Shared Documents/General/Pursuit Management Insights/Static Files/" = #"Filtered Rows"{[Name="Static Mappings - DO NOT MOVE OR DELETE THIS FILE.xlsx",#"Folder Path"="https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/Shared Documents/General/Pursuit Management Insights/Static Files/"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"Static Mappings-DO NOT MOVE OR DELETE THIS FILE.xlsx_https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/Shared Documents/General/Pursuit Management Insights/Static Files/"),
				    #"Country Flags_Sheet" = #"Imported Excel Workbook"{[Item="Country Flags",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Country Flags_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Subsidiary", type text}, {"Image", type text}, {"Timezone", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

