table 'Static-Timezone Leaders'
	isHidden
	lineageTag: d53d5225-331e-4f09-b341-098bf9281fce

	column Alias
		dataType: string
		isHidden
		lineageTag: 13f78295-5d17-4e0b-b8bb-58b640779719
		summarizeBy: none
		sourceColumn: Alias

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Timezone
		dataType: string
		isHidden
		lineageTag: 8316a476-e87d-4741-bd17-805152dea97c
		summarizeBy: none
		sourceColumn: Timezone

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Static-Timezone Leaders-5a3059bb-abe3-4ed0-b3d5-4d753708bc1a' = m
		mode: import
		queryGroup: 'Org Related Queries'
		source =
				let
				   Source = SharePoint.Files("https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "Static Mappings - DO NOT MOVE OR DELETE THIS FILE.xlsx")),
				    #"Static Mappings- DO NOT MOVE OR DELETE THIS FILE.xlsx_https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/Shared Documents/General/Pursuit Management Insights/Static Files/" = #"Filtered Rows"{[Name="Static Mappings - DO NOT MOVE OR DELETE THIS FILE.xlsx",#"Folder Path"="https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/Shared Documents/General/Pursuit Management Insights/Static Files/"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"Static Mappings- DO NOT MOVE OR DELETE THIS FILE.xlsx_https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/Shared Documents/General/Pursuit Management Insights/Static Files/"),
				    #"Timezone Leaders_Sheet" = #"Imported Excel Workbook"{[Item="Timezone Leaders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Timezone Leaders_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Alias", type text}, {"Timezone", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

