table 'Static-Low Complexity Mgr'
	isHidden
	lineageTag: 4e29e3bd-c813-4e73-9af2-417ca8656342

	column 'Mgr Name'
		dataType: string
		isHidden
		lineageTag: bf28dd95-fdb5-43f3-85a6-efe68bbcc77a
		summarizeBy: none
		sourceColumn: Mgr Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Timezone
		dataType: string
		lineageTag: 122086e0-4f01-4d17-bbee-4b27bb721637
		summarizeBy: none
		sourceColumn: Timezone

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 337af9bd-8a48-4457-858a-fffa5dba5565
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	partition 'Static-Low Complexity Mgr-b2766f7d-0cd7-4f0e-bcbc-f2ed77c4a20f' = m
		mode: import
		queryGroup: 'Excel Org Alignment Tables'
		source =
				let
				    Source = SharePoint.Files("https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "Static Mappings - DO NOT MOVE OR DELETE THIS FILE.xlsx")),
				    #"Static Mappings-DO NOT MOVE OR DELETE THIS FILE.xlsx_https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/Shared Documents/General/Pursuit Management Insights/Static Files/" = #"Filtered Rows"{[Name="Static Mappings - DO NOT MOVE OR DELETE THIS FILE.xlsx",#"Folder Path"="https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/Shared Documents/General/Pursuit Management Insights/Static Files/"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"Static Mappings-DO NOT MOVE OR DELETE THIS FILE.xlsx_https://microsoftapc.sharepoint.com/teams/PursuitManagementInsights/Shared Documents/General/Pursuit Management Insights/Static Files/"),
				    #"Low Complexity Mgr_Sheet" = #"Imported Excel Workbook"{[Item="Low Complexity Mgr",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Low Complexity Mgr_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Mgr Name", type text}, {"Timezone", type text}, {"Column3", type any}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

